name: GitHubAction Demo Project
 
on:
  push:
    branches:
     - main
  workflow_dispatch:
 
jobs:
  build-and-deploy:    
    runs-on: self-hosted
 
    steps:
    - uses: actions/checkout@master
 
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'
 
    
    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ${{env.DOTNET_ROOT}}/GitHubActionDemo/* C:\inetpub\wwwroot\GitHubActionDemo -Recurse -Force
        iisreset /start
