name: GitHubAction Demo Project
 
on:
  push:
    branches:
     - main
  workflow_dispatch:
 
jobs:
  build-and-deploy:    
    runs-on: self-hosted
 
  
   
    
    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ${{env.DOTNET_ROOT}}/GitHubActionDemo/* C:\inetpub\wwwroot\GitHubActionDemo -Recurse -Force
        iisreset /start
